api_platform:
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
