api_platform:
    title: 'Fight2Feed API'
    description: 'API providing data to the Fight2Feed mobile application'
    version: '1.0.0'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/DTO'
    eager_loading:
        enabled: true
        force_eager: false
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
