vich_uploader:
    db_driver: orm
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            namer: vich_uploader.namer_uniqid
            directory_namer: vich_uploader.directory_namer_subdir