# Read the documentation: https://github.com/IndraGunawan/api-rate-limit-bundle/blob/master/Resources/doc/usage.md
indragunawan_api_rate_limit:
    enabled: true
    cache: ~
    throttle:
        default:
            limit: 1 # max attempts per period
            period: 1 # in seconds
    #     sort: 'rate-limit-desc'
